import matplotlib.pyplot as plt
import numpy as np
def plotMTFs(sar):
    # fig1, ((axTilt, axHydrodynamic, axRB, axVB), (axTiltPhase, axHydrodynamicPhase, axRBPhase, axVBPhase))=plt.subplots(2,4)
    fig1, ((axTilt, axHydrodynamic), (axRB, axVB))=plt.subplots(2,2)
    axTilt.pcolor(sar.kx, sar.ky, abs(sar.tilt_mtf()), cmap='viridis')
    axTiltContour=axTilt.contour(sar.kx, sar.ky, abs(sar.tilt_mtf()), colors='w')
    axTilt.clabel(axTiltContour, axTiltContour.levels, inline=True, fontsize=10)
    axTilt.set_title("Tilt MTF")
    axTilt.set_xlabel("Azimuth Wavenumber")
    axTilt.set_ylabel("Range Wavenumber")
    # axTiltPhase.pcolor(sar.kx, sar.ky, np.angle(sar.tilt_mtf()))
    # axTiltPhase.contour(sar.kx, sar.ky, np.angle(sar.tilt_mtf()), colors='w')
    # axTiltPhase.set_title("Tilt MTF")
    # axTiltPhase.set_xlabel("Azimuth Wavenumber")
    # axTiltPhase.set_ylabel("Range Wavenumber")
    axHydrodynamic.pcolor(sar.kx, sar.ky, abs(sar.hydrodynamic_mtf()))
    axHydrodynamicContour=axHydrodynamic.contour(sar.kx, sar.ky, abs(sar.hydrodynamic_mtf()), colors='w')
    axHydrodynamic.clabel(axHydrodynamicContour, axHydrodynamicContour.levels, inline=True, fontsize=10)
    axHydrodynamic.set_title("Hydrodynamic MTF")
    axHydrodynamic.set_xlabel("Azimuth Wavenumber")
    axHydrodynamic.set_ylabel("Range Wavenumber")
    # axHydrodynamicPhase.pcolor(sar.kx, sar.ky, np.angle(sar.hydrodynamic_mtf()))
    # axHydrodynamicPhase.contour(sar.kx, sar.ky, np.angle(sar.hydrodynamic_mtf()), colors='w')
    # axHydrodynamicPhase.set_title("Tilt MTF")
    # axHydrodynamicPhase.set_xlabel("Azimuth Wavenumber")
    # axHydrodynamicPhase.set_ylabel("Range Wavenumber")
    axRB.pcolor(sar.kx, sar.ky, abs(sar.range_bunching_mtf()))
    axRBContour=axRB.contour(sar.kx, sar.ky, abs(sar.range_bunching_mtf()), colors='w')
    axRB.clabel(axRBContour, axRBContour.levels, inline=True, fontsize=10)
    axRB.set_title("Range Bunching MTF")
    axRB.set_xlabel("Azimuth Wavenumber")
    axRB.set_ylabel("Range Wavenumber")
    # axRBPhase.pcolor(sar.kx, sar.ky, np.angle(sar.range_bunching_mtf()))
    # axRBPhase.contour(sar.kx, sar.ky, np.angle(sar.range_bunching_mtf()), colors='w')
    # axRBPhase.set_title("Tilt MTF")
    # axRBPhase.set_xlabel("Azimuth Wavenumber")
    # axRBPhase.set_ylabel("Range Wavenumber")
    axVB.pcolor(sar.kx, sar.ky, abs(sar.velocity_bunching_mtf()))
    axVBContour=axVB.contour(sar.kx, sar.ky, abs(sar.velocity_bunching_mtf()), colors='w')
    axVB.clabel(axVBContour, axVBContour.levels, inline=True, fontsize=10)
    axVB.set_title("Velociy Bunching MTF")
    axVB.set_xlabel("Azimuth Wavenumber")
    axVB.set_ylabel("Range Wavenumber")
    # axVBPhase.pcolor(sar.kx, sar.ky, np.angle(sar.velocity_bunching_mtf()))
    # axVBPhase.contour(sar.kx, sar.ky, np.angle(sar.velocity_bunching_mtf()), colors='w')
    # axVBPhase.set_title("Tilt MTF")
    # axVBPhase.set_xlabel("Azimuth Wavenumber")
    # axVBPhase.set_ylabel("Range Wavenumber")

    fig2, (axOrbitalMTF, axOrbital)=plt.subplots(1,2)
    axOrbitalMTF.pcolor(sar.kx, sar.ky, abs(sar.orbital_velocity_mtf()), cmap='gist_gray')
    axOVContour=axOrbitalMTF.contour(sar.kx, sar.ky, abs(sar.orbital_velocity_mtf()), colors='w')
    axOrbitalMTF.clabel(axOVContour, axOVContour.levels, inline=True, fontsize=10)
    axOrbitalMTF.set_title("Orbital Velocity MTF")
    axOrbitalMTF.set_xlabel("Azimuth Wavenumber")
    axOrbitalMTF.set_ylabel("Range Wavenumber")
    plotColorbar=axOrbital.imshow(sar.mean_orbital_velocity(), origin='lower')
    plt.colorbar(plotColorbar, ax=axOrbital)
    # axOrbital.pcolor(sar.kx, sar.ky, abs(sar.orbital_velocity_mtf()), cmap='gist_gray')
    # axOrbital.contour(sar.kx, sar.ky, abs(sar.orbital_velocity_mtf()), colors='w')
    # axOrbital.set_title("Orbital Velocity MTF")
    # axOrbital.set_xlabel("Azimuth Wavenumber")
    # axOrbital.set_ylabel("Range Wavenumber")

    fig3, (axRARAbs, axRarPhase)=plt.subplots(1,2)
    axRARAbsPlot=axRARAbs.pcolor(sar.kx, sar.ky, abs(sar.RAR_MTF()), cmap='gist_gray')
    absContour=axRARAbs.contour(sar.kx, sar.ky, abs(sar.RAR_MTF()),20, colors='w')
    plt.colorbar(axRARAbsPlot, ax=axRARAbs)
    axRARAbs.clabel(absContour, absContour.levels, inline=True, fontsize=10)
    axRARAbs.set_title("RAR MTF")
    axRARAbs.set_xlabel("Azimuth Wavenumber")
    axRARAbs.set_ylabel("Range Wavenumber")
    axRarPhasePlot=axRarPhase.pcolor(sar.kx, sar.ky, abs(np.angle(sar.RAR_MTF())), cmap='gist_gray')
    phaseContour=axRarPhase.contour(sar.kx, sar.ky, np.rad2deg(abs(np.angle(sar.RAR_MTF()))), 20, colors='w')
    plt.colorbar(axRarPhasePlot, ax=axRarPhase)
    axRarPhase.clabel(phaseContour, phaseContour.levels, inline=True, fontsize=10)
    axRarPhase.set_title("RAR MTF")
    axRarPhase.set_xlabel("Azimuth Wavenumber")
    axRarPhase.set_ylabel("Range Wavenumber")

    fig4, (axSARAbs, axSARPhase)=plt.subplots(1,2)
    # axSARAbs.plot(sar.tilt_mtf())
    axRARAbsPlot=axSARAbs.pcolor(sar.kx, sar.ky, abs(sar.SAR_MTF()), cmap='gist_gray')
    absContourSAR=axSARAbs.contour(sar.kx, sar.ky, abs(sar.SAR_MTF()),20, colors='w')
    plt.colorbar(axRARAbsPlot, ax=axSARAbs)
    axSARAbs.clabel(absContourSAR, absContourSAR.levels, inline=True, fontsize=10)
    axSARAbs.set_title("SAR MTF")
    axSARAbs.set_xlabel("Azimuth Wavenumber")
    axSARAbs.set_ylabel("Range Wavenumber")
    axsarPhasePlot=axSARPhase.pcolor(sar.kx, sar.ky, abs(np.angle(sar.SAR_MTF())), cmap='gist_gray')
    phaseContourSAR=axSARPhase.contour(sar.kx, sar.ky, np.rad2deg(abs(np.angle(sar.SAR_MTF()))), 20, colors='w')
    plt.colorbar(axsarPhasePlot, ax=axSARPhase)
    axSARPhase.clabel(phaseContourSAR, phaseContourSAR.levels, inline=True, fontsize=10)
    axSARPhase.set_title("SAR MTF")
    axSARPhase.set_xlabel("Azimuth Wavenumber")
    axSARPhase.set_ylabel("Range Wavenumber")

    # fig4, (sigmaPLot)=plt.subplots(1,1)
    # sigmaPLot.plot((sar.v_covariance(0)[128,:]))
    # sigmaPLot.plot((sar.v_covariance(0)[:,128]))

    # plt.colorbar(sigmaColorbar, ax=sigmaPLot)

def plotModulations(sar):
    fig, (ax)=plt.subplots(1)
    ax.plot(sar.surface[:,sar.N_x-1], label="surface")
    # ax.plot(sar.NRCS()[:,sar.N_y-1], label="NRCS")
    tilt=np.real(np.fft.ifft2(np.fft.ifftshift(sar.tilt_mtf()*np.fft.fftshift(np.fft.fft2(sar.surface)))))
    ax.plot(tilt[:,sar.N_x-1], label="tilt")
    hydrodynamic=np.real(np.fft.ifft2(np.fft.ifftshift(sar.hydrodynamic_mtf()*np.fft.fftshift(np.fft.fft2(sar.surface)))))
    ax.plot(hydrodynamic[:,sar.N_x-1], label="hydrodynamic")
    rb=np.real(np.fft.ifft2(np.fft.ifftshift(sar.range_bunching_mtf()*np.fft.fftshift(np.fft.fft2(sar.surface)))))
    ax.plot(rb[:,sar.N_x-1], label="range bunching")
    vb=np.real(np.fft.ifft2(np.fft.ifftshift(sar.velocity_bunching_mtf()*np.fft.fftshift(np.fft.fft2(sar.surface)))))
    ax.plot(vb[:,sar.N_x-1], label="velocity bunching")
    plt.legend()

def animate(Z):
    from matplotlib.animation import FuncAnimation
    # Create a figure and axis
    fig, ax = plt.subplots()

    # Initialize imshow plot
    img = ax.imshow(Z[0,:,:], animated=True, origin='lower')

    # Define the update function for animation
    def update(frame):
        # Update data with random values
        img.set_array(Z[frame,:,:])
        return img,

    # Create animation
    ani = FuncAnimation(fig, update, frames=Z.shape[0], interval=200, blit=True)
    plt.show()

def plotSpectras(sar):
    fig, ((ax1,ax2, ax3), (ax4, ax5, ax6))=plt.subplots(2, 3)

    ax1.contour(sar.kx, sar.ky, abs(sar.PSI))#, extent=(sar.kx.min(),sar.kx.max(),sar.ky.min(),sar.ky.max()))
    ax1.set_title("Original Spectrum")
    ax1.set_xlabel("Azimuth Wavenumber")
    ax1.set_ylabel("Range Wavenumber")
    ax2.contour(sar.kx, sar.ky,abs(np.fft.fftshift(np.fft.fft2(sar.surface))))#, extent=(sar.kx.min(),sar.kx.max(),sar.ky.min(),sar.ky.max()))
    ax2.set_title("Sea surface Spectrum")
    ax2.set_xlabel("Azimuth Wavenumber")
    ax2.set_ylabel("Range Wavenumber")
    ax3.contour(sar.kx, sar.ky,abs(np.fft.fftshift(np.fft.fft2(sar.I-np.mean(sar.I)))))#, extent=(sar.kx.min(),sar.kx.max(),sar.ky.min(),sar.ky.max()))
    ax3.set_title("SAR Spectrum")
    ax3.set_xlabel("Azimuth Wavenumber")
    ax3.set_ylabel("Range Wavenumber")
    ax4.contour(sar.kx, sar.ky,abs(sar.linear_mapping_transform()))#, extent=(sar.kx.min(),sar.kx.max(),sar.ky.min(),sar.ky.max()))
    ax4.set_title("Linear SAR Mapping")
    ax4.set_xlabel("Azimuth Wavenumber")
    ax4.set_ylabel("Range Wavenumber")
    ax5.contour(sar.kx, sar.ky,abs(sar.quasilinear_mapping_transform()))
    ax5.set_title("Quasi Linear SAR Mapping")
    ax5.set_xlabel("Azimuth Wavenumber")
    ax5.set_ylabel("Range Wavenumber")
    ax6.contour(sar.kx, sar.ky,abs((sar.nonlinear_mapping_transform(1))))
    ax6.set_title("Non Linear SAR Mapping")
    ax6.set_xlabel("Azimuth Wavenumber")
    ax6.set_ylabel("Range Wavenumber")

def plotSurfaceSAR(sar):
    fig, (axSurface,axSurfaceRAR,axSurfaceSAR)=plt.subplots(1,3)
    axSurface.imshow(sar.surface, origin='lower')
    axSurface.set_xlabel("Azimuth")
    axSurface.set_ylabel("Range")
    axSurface.set_title("Ocean Wave Field")
    axSurfaceRAR.imshow(sar.sigma, origin='lower')
    axSurfaceRAR.set_xlabel("Azimuth")
    axSurfaceRAR.set_ylabel("Range")
    axSurfaceRAR.set_title("RAR Image")
    axSurfaceSAR.imshow(sar.I, origin='lower')
    axSurfaceSAR.set_xlabel("Azimuth")
    axSurfaceSAR.set_ylabel("Range")
    axSurfaceSAR.set_title("SAR Image")

def coherence_time():
    from scipy import special
    fig, ax=plt.subplots(1,1)
    wind_speed_19_5=np.logspace(0,1.2,100)#self.wind_speed*(19.5/10)**(1/7)
    frequencies=np.array([1.579,2.671,5.3,10,14,35])
    for f in frequencies:
        light_speed=299792458
        wavelength=light_speed/(f*1e9)
        print(wavelength)
        ts=3*wavelength/wind_speed_19_5*special.erf(2.7*30/wind_speed_19_5**2)**(-1/2)
        ax.plot(wind_speed_19_5,ts*1000,label=f"{f} GHz")

    ax.set_yscale('log')
    ax.set_xscale('log')
    ax.set_xlabel("Windspeeds [m/s]")
    ax.set_ylabel("Coherence Time [ms]")
    ax.set_title("Coherence time")
    plt.legend()
    plt.show()